### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by TinaNeik** [StoreyLab/qvalue#13]
Hi, 

I have a set of 27577 p-values obtained from GWAS MLM Q + K in TASSEL. I want to perform FDR on these p-values using qvalue package in R. May I ask, what is the input data format? I opened the data "hedenfalk" in R but don't understand how is it formatted. Could you please help me?

Thank you.

**Comment by ajbass** [comment]
The `qvalue` function requires a vector of p-values. You can access the p-values from the hedenfalk example as 

```
pvals <- hedenfalk$p
```
