### ISSUE TITLE
function "qvalue_truncp" has been removed?

### ISSUE THREAD

**Issue by jrager** [StoreyLab/qvalue#21]
We have been running the qvalue package smoothly, and have in some instances incorporated the function "qvalue_truncp" to deal with the issue, as explained in (among others):
https://github.com/StoreyLab/qvalue/issues/11

However, recently R is throwing me the error, "Error in qvalue_truncp() could not find function "qvalue_truncp"

I tried re-installing the qvalue package, which didn't help. Where did this function go?

**Comment by ajbass** [comment]
It's still there. Did you install `qvalue` from github?

```
library(devtools)
install_github("StoreyLab/qvalue")

library(qvalue)
qout <- qvalue_truncp(runif(100, max=0.9))
```

**Comment by jrager** [comment]
Yes – I just ran the lines of coded provided below and received:

> library(qvalue)
> qout <- qvalue_truncp(runif(100, max=0.9))
Error in qvalue_truncp(runif(100, max = 0.9)) : could not find function "qvalue_truncp"

Thank you for the feedback!!

Julia E. Rager, PhD, MSEE
Assistant Professor
Institute for Environmental Health Solutions
Department of Environmental Sciences and Engineering
UNC Gillings School of Global Public Health, Chapel Hill, NC

Office: 347 Rosenau
Mailing: 135 Dauer Drive, CB 7431, Chapel Hill, NC 27599
Phone: 919-966-4410

**Comment by jrager** [comment]
> It's still there. Did you install `qvalue` from github?
> 
> ```
> library(devtools)
> install_github("StoreyLab/qvalue")
> 
> library(qvalue)
> qout <- qvalue_truncp(runif(100, max=0.9))
> ```

**Comment by jrager** [comment]
Yes – I just ran the lines of coded provided below and received:
 library(qvalue)
 qout <- qvalue_truncp(runif(100, max=0.9))
Error in qvalue_truncp(runif(100, max = 0.9)) : could not find function "qvalue_truncp"

Thank you for the feedback!!

**Comment by jrager** [comment]
Sorry I didn’t mean to close this thread – was just trying to edit my comment that still remains and issue below:


Yes – I just ran the lines of coded provided below and received:

> library(qvalue)
> qout <- qvalue_truncp(runif(100, max=0.9))
Error in qvalue_truncp(runif(100, max = 0.9)) : could not find function "qvalue_truncp"

Thank you for the feedback!!

**Comment by ajbass** [comment]
Can you send over:

```
library(qvalue)
library(devtools)
sessionInfo()
```

You should see version `qvalue 2.15.0`.

**Comment by jrager** [comment]
Yep, I see: other attached packages:
[1] devtools_2.2.1    usethis_1.5.1     qvalue_2.15.0     reshape2_1.4.3    dplyr_0.8.3       ggplot2_3.2.1     data.table_1.12.8

I also tried installing it using install_github("jdstorey/qvalue"), but got the same result. I had a student run the lines that you provided on a separate computer, and it worked for him, so it is something that's happening on my computer. Let me know if anything comes to mind, but if not, I'll just have the code run on a separate computer. Thanks!
