### ISSUE TITLE
Error in quantile.default(pi0, prob = 0.1) 

### ISSUE THREAD

**Issue by wz115** [StoreyLab/qvalue#22]
Error in quantile.default(pi0, prob = 0.1) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE.
the command like this:
library(qvalue)

p=c(1.156796010154508e-19,
    0.005397598467051851,
    1.2983991541118467e-07,
    0.6676365826170595,
    0.003076972380373958,
    0.44596303111439095,
    0.2807926301003788,
    0.01113485576244273,
    0.02181395118917531,
    0.35265771372995536,
    0.2819423459077349,
    0.23581109340680287,
    4.686170103039069e-06,
    0.438886819980965,
    0.046353512839543864,
    0.020394957496359084,
    0.02606532301233144,
    0.42683959427873563,
    5.682845790385846e-05,
    0.6083562890394267,
    0.000738733703839064,
    9.107367816885332e-16,
    0.6604549539975475)
q=qvalue(p,pi0.method="bootstrap")

**Comment by ajbass** [comment]
Not enough p-values to estimate the proportion of truly null tests. You can the run the package as follows:
```
q=qvalue(p,pi0 = 1)
```

**Comment by wz115** [comment]
Thanks!

**Comment by Junjun-Xu** [comment]
Hi,
Now, I have very few p-values and get the same error, but I want to calculate the qvalue. If I set the q=qvalue(p,pi0 = 1), is there any influence on my result?
Thanks
Jun
