### ISSUE TITLE
clarification question

### ISSUE THREAD

**Issue by devonorourke** [StoreyLab/qvalue#23]
Thanks for creating and maintaining a great piece of software.
As a very novice user of q values and statistics generally I was hoping you could help me understand the difference between the `summary` and `plot` functions outputs. In the vignette that uses the **hedenfalk** dataset, a portion of the summary output looks like this:
```
##Cumulative number of significant calls:####           
          <1e-04 <0.001 <0.01 <0.025 <0.05 <0.1
p-value       15     76   265    424   605  868
q-value        0      0     1     73   162  319
local FDR      0      0     3     30    85  167
```

My takeaway from that table was that for a given FDR level (the columns), we would expect N significant sites (rows) for the p and q-values listed. For instance, at and FDR level of **0.05**, we might expect 605 significant p-value tests, while just 162 positive q-value tests.

I'm unclear what the last row, the _local FDR_, is indicating. These values in this vignette are usually about half of the value reported in the q-value of a similar column (I see the same effect in my own data). At first I thought this represented the estimated number of false positives, but then after reading on in the vignette, you show how to find this answer exactly in section 5.4 with the `plot` function.

However, if I look at that plot in the vignette, I noticed that at the point where there are about 160 significant tests, we'd expect only about 5 false positives, not the ~85 that are indicated in the table in the *local FDR* row... 
![Screen Shot 2020-03-27 at 1 18 43 PM](https://user-images.githubusercontent.com/11182172/77782414-a5757900-702d-11ea-8261-c1b21d308586.png)

Thus it seems like my understanding of what the local FDR row in the `summary` output is incorrect.

Thanks for any insights you can offer,

Devon

**Comment by jdstorey** [comment]
https://jdstorey.org/fas/multiple-testing.html#local-fdr
