### ISSUE TITLE
qvalue and lfdr are smaller than origin p values

### ISSUE THREAD

**Issue by wt12318** [StoreyLab/qvalue#25]
Hi

I used the `qvalue` function to calculate q values from a list of p values, but the 86% of q value is smaller than 0.05, while only 12% origin  p value is smaller than 0.05. Why this happened and how can I handle this problem. Could you give some suggestions?

Thanks
[p_value.zip](https://github.com/StoreyLab/qvalue/files/5521183/p_value.zip)

**Comment by jdstorey** [comment]
https://github.com/StoreyLab/qvalue#frequently-asked-questions
