### ISSUE TITLE
Pi0 estimation method?

### ISSUE THREAD

**Issue by mrForce** [StoreyLab/qvalue#29]
Hi,

I read the Direct FDR paper, and then looked at pi0est.R, and I have some questions about it. First, while it mentions bootstrapping as a method, but I don't see any resampling occurring in the code. Second, the formula for the MSE (to be minimized) used in the code is:

```mse <- (W / (m ^ 2 * (1 - lambda) ^ 2)) * (1 - W / m) + (pi0 - minpi0) ^ 2```

Where does this come from? It doesn't seem to be mentioned explicitly in any of the references listed in the top. I tried to expand out equation 27 from the direct FDR paper, but got a different (I think) result than what's in the code, though it's possible (likely) that I screwed up the math.

**Comment by jdstorey** [comment]
We derived a closed form solution for the bootstrap, so resampling is no longer necessary.
