### ISSUE TITLE
q value doubt

### ISSUE THREAD

**Issue by a-espuela** [StoreyLab/qvalue#31]
Hi,

I have been using the qvalue R package and I came across an unusual behaviour.
My input is a list of p-values and what I want to do is to adjust for multiple comparisons.

I have used the _qvalue_ function, to extract afterwards the q-values from the generated object _(qvalues_ and _lfdr_).

For most of my analyses the q-values are bigger than the original ones (which I think is the normal output) but for one particular analysis, Storey's q-values and lfdr are smaller.

I am wondering if this is normal.
Besides, are there any assumptions that this type of approach has that I should be concern of?
I have checked the distribution of p-values and it seems OK.

Thanks in advance,
Antonio

**Comment by jdstorey** [comment]
https://github.com/StoreyLab/qvalue#frequently-asked-questions
