### ISSUE TITLE
Request to Replace Sweave Vignettes with R Markdown

### ISSUE THREAD

**Issue by sonali8434** [StoreyLab/qvalue#37]
Hello @jdstorey @rileysg  , I'm a [Sweave2Rmd](https://github.com/Bioconductor/sweave2rmd) volunteer. @jwokaty and I are trying to replace Bioconductor Sweave vignettes with R Markdown. It has many advantages over Sweave vignettes, such as R Markdown converts to HTML, uses BiocStyle, and is easier to maintain.

Would you consider accepting a pull request for the R Markdown version of "qvalue/vignettes/qvalue.Rnw" from one of our volunteers?

We'll ask you to review and accept the pull request. You'll also need to bump the version number in your DESCRIPTION file so that the Bioconductor build machines will recognize that a new version is available.

Thank you for your time, I look forward to your response.

**Comment by jdstorey** [comment]
Yes, I will consider it. Thanks.
