### ISSUE TITLE
stop + cat problem found

### ISSUE THREAD

**Issue by dgarrimar** [StoreyLab/qvalue#5]
Hi,

i found this piece of code within the pi0est function (around line 92), after having some trouble with tryCatch:

stop(cat("ERROR:", paste("length(lambda)=", ll, ".", sep=""), "If length of lambda greater than 1,",
"you need at least 4 values."))

I think it would be better to use stop + sprintf cause otherwise it is difficult to catch this error, as it is not treated as an error but printed to the screen.

Thanks,

Diego

**Comment by ajbass** [comment]
Good catch. Will fix soon.

Thanks,
Andrew
