### ISSUE TITLE
Availability of the functional FDR method?

### ISSUE THREAD

**Issue by pkimes** [StoreyLab/qvalue#8]
I'm interested in testing out the functional FDR methods described in [this preprint on bioRxiv](https://www.biorxiv.org/content/early/2017/12/30/241133). I saw the following at the end of the manuscript:

> The methods described in this paper will be made available in the qvalue R package, available at
https://github.com/StoreyLab/qvalue (most recent version) or https://www.bioconductor.org/
packages/release/bioc/html/qvalue.html (official release).

I understand that the preprint was posted fairly recently, but any idea when the new methods will be incorporated in the package? Or is it already available somewhere else (a fork?) that I might have missed? Thanks!

**Comment by jdstorey** [comment]
We're working on it now. You can watch this repo if you want to be notified when the updates are completed.

**Comment by pkimes** [comment]
Thanks!

**Comment by ajbass** [comment]
https://github.com/StoreyLab/fFDR
